export enum CREATE_RECIPE {
  START = 'CREATE_RECIPE_START',
  SUCCESS = 'CREATE_RECIPE_SUCCESS',
  FAIL = 'CREATE_RECIPE_FAIL'
}

export enum READ_RECIPE {
  _START = 'READ_RECIPE_START',
  _SUCCESS = 'READ_RECIPE_SUCCESS',
  _FAIL = 'READ_RECIPE_FAIL'
}

export enum UPDATE_RECIPE {
  START = 'UPDATE_RECIPE_START',
  SUCCESS = 'UPDATE_RECIPE_SUCCESS',
  FAIL = 'UPDATE_RECIPE_FAIL'
}

export enum DELETE_RECIPE {
  START = 'DELETE_RECIPE_START',
  SUCCESS = 'DELETE_RECIPE_SUCCESS',
  FAIL = 'DELETE_RECIPE_FAIL'
}